"""Add workflow system tables for 8-phase AI dashboard platform

Revision ID: 8db54fb53bdf
Revises: d31687cfefd8
Create Date: 2025-07-14 17:32:43.632353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db54fb53bdf'
down_revision: Union[str, None] = 'd31687cfefd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
