"""Add user authentication and dashboard user relationship

Revision ID: d31687cfefd8
Revises: 4f9ceb9313e1
Create Date: 2025-05-27 10:42:03.937401

"""
import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision: str = 'd31687cfefd8'
down_revision: Union[str, None] = '4f9ceb9313e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create users table first
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Create a default admin user for existing dashboards
    users_table = table('users',
        column('id', sa.Integer),
        column('user_id', sa.String),
        column('email', sa.String),
        column('username', sa.String),
        column('full_name', sa.String),
        column('hashed_password', sa.String),
        column('is_active', sa.Boolean),
        column('is_admin', sa.Boolean)
    )

    # Insert default admin user (password is 'admin123' hashed with bcrypt)
    op.execute(
        users_table.insert().values(
            user_id=str(uuid.uuid4()),
            email='admin@clickdash.com',
            username='admin',
            full_name='System Administrator',
            hashed_password='$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBdXwtO5S5EM9S',  # admin123
            is_active=True,
            is_admin=True
        )
    )

    # Add user_id column as nullable first
    op.add_column('dashboards', sa.Column('user_id', sa.Integer(), nullable=True))

    # Update existing dashboards to belong to the admin user
    connection = op.get_bind()
    admin_user_id = connection.execute(
        sa.text("SELECT id FROM users WHERE username = 'admin'")
    ).scalar()

    if admin_user_id:
        connection.execute(
            sa.text("UPDATE dashboards SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": admin_user_id}
        )

    # Now make user_id NOT NULL
    op.alter_column('dashboards', 'user_id', nullable=False)

    # Create foreign key
    op.create_foreign_key('fk_dashboards_user_id', 'dashboards', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dashboards_user_id', 'dashboards', type_='foreignkey')
    op.drop_column('dashboards', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
